

<div class="container">
    <section class="mt-4 p-4 border border-2 border-sucess rounded ">
        <div class="d-flex justify-content-between align-items-center">
            <h1 class=""><i class="bi bi-people-fill"></i> Palestrantes</h1>
            <a href="cadastrar" class="btn btn-primary"><i class="bi bi-plus-lg"></i> Novo Palestrante</a>
        </div>
        <table class="table table-striped table-hover ">
            <thead>
                <tr>
                    <th class="text-start" scope="col">#</th>
                    <th class="text-center" scope="col">Foto</th>
                    <th class="text-center" scope="col">Nome</th>
                    <th class="text-center" scope="col">E-mail</th>
                    <th class="text-center" scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
         <?php if(count($palestrantes) == 0): ?>
                <tr>
                    <td colspan="5" class="text-center">Nenhum palestrante cadastrado</td>
                </tr>
                <?php else: ?>
                <?php foreach ($palestrantes as $palestrante): ?>

                <tr>
                    <th class="text-start" scope="row"><?= htmlspecialchars($palestrante['id']) ?></th>
                    <td class="text-center">
                        <img src="<?= htmlspecialchars($palestrante['foto']) ?>" alt="Foto de <?= htmlspecialchars($palestrante['foto']) ?>" class="img-fluid rounded" style="max-width: 50px; max-height: 50px;">  <!-- <tr> -->
                    </td>
                    <td class="text-center"><?= htmlspecialchars($palestrante['nome']) ?></td>
                    <td class="text-center"><?= htmlspecialchars($palestrante['email']) ?></td>
                    <td class="text-center">
                        <a href="editar/?id=<?= $palestrante['id']?>"class="btn btn-warning">
                            <i class="bi bi-pencil-square"></i>
                        </a>
                        <button class="btn btn-danger" onclick="prepareDelete(<?= $palestrante['id']?>)">
                            <i class="bi bi-trash3"></i>
                        </button>
                    </td>
                </tr>
                <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
        </table>
    </section>
</div>

<script src="/validations/validations.js"> </script>

<script>
    const prepareDelete = (id) => {
        
        if(confirm("Tem certeza que deseja excluir este palestrante?")) {
            confirmDelete('excluir/?id='+id);
        }
    }

</script>