<div class="container">
    <section class="mt-4 p-4 border border-2 border-sucess rounded ">
        <div class="d-flex justify-content-between align-items-center">
            <h1 class=""><i class="bi bi-people-fill"></i> Palestrantes</h1>
            <a href="add" class="btn btn-primary"><i class="bi bi-plus-lg"></i> Novo Palestrante</a>
        </div>
        <table class="table table-striped table-hover ">
            <thead>
                <tr>
                    <th class="text-start" scope="col">#</th>
                    <th class="text-center" scope="col">Foto</th>
                    <th class="text-center" scope="col">Nome</th>
                    <th class="text-center" scope="col">E-mail</th>
                    <th class="text-center" scope="col">Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($usuarios as $usuario): ?>

                <tr>
                    <th class="text-start" scope="row"><?= htmlspecialchars($usuario['id']) ?></th>
                    <td class="text-center">
                        <img src="<?= htmlspecialchars($usuario['foto']) ?>" alt="Foto de <?= htmlspecialchars($usuario['foto']) ?>" class="img-fluid rounded" style="max-width: 50px; max-height: 50px;">  <!-- <tr> -->
                    </td>
                    <td class="text-center"><?= htmlspecialchars($usuario['nome']) ?></td>
                    <td class="text-center"><?= htmlspecialchars($usuario['email']) ?></td>
                    <td class="text-center">
                        <button class="btn btn-warning">
                            <i class="bi bi-pencil-square"></i>
                        </button>
                        <button class="btn btn-danger">
                            <i class="bi bi-trash3"></i>
                        </button>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </section>
</div>